const LANGUAGE_EXTENSION_MAP: Record<string, string> = {
  ansi: "txt",
  bash: "sh",
  c: "c",
  "c++": "cpp",
  "c#": "cs",
  clojure: "clj",
  coffee: "coffee",
  coffeescript: "coffee",
  cpp: "cpp",
  cs: "cs",
  csharp: "cs",
  css: "css",
  dart: "dart",
  diff: "diff",
  docker: "dockerfile",
  dockerfile: "dockerfile",
  elixir: "ex",
  elm: "elm",
  go: "go",
  golang: "go",
  graphql: "graphql",
  haskell: "hs",
  hcl: "hcl",
  html: "html",
  ini: "ini",
  java: "java",
  javascript: "js",
  js: "js",
  json: "json",
  jsx: "jsx",
  kotlin: "kt",
  lua: "lua",
  make: "mk",
  makefile: "mk",
  markdown: "md",
  md: "md",
  objectivec: "m",
  patch: "patch",
  perl: "pl",
  php: "php",
  plaintext: "txt",
  powershell: "ps1",
  protobuf: "proto",
  proto: "proto",
  pwsh: "ps1",
  py: "py",
  python: "py",
  r: "r",
  ruby: "rb",
  rust: "rs",
  scala: "scala",
  shell: "sh",
  shellscript: "sh",
  sh: "sh",
  solidity: "sol",
  sql: "sql",
  swift: "swift",
  svelte: "svelte",
  terraform: "tf",
  text: "txt",
  toml: "toml",
  ts: "ts",
  tsx: "tsx",
  txt: "txt",
  typescript: "ts",
  vue: "vue",
  xml: "xml",
  yaml: "yml",
  yml: "yml",
  zsh: "sh",
};

export function getCodeDownloadFilename(
  language?: string,
  fallbackExtension = "txt",
): string {
  const normalizedLanguage = language?.trim().toLowerCase();
  const extension = normalizedLanguage
    ? LANGUAGE_EXTENSION_MAP[normalizedLanguage] || normalizedLanguage
    : fallbackExtension;

  return `code.${extension}`;
}
