const E2B_VCPU_COUNT = 4;
const E2B_MEMORY_GIB = 4;
const E2B_COST_PER_VCPU_SECOND_USD = 0.000014;
const E2B_COST_PER_GIB_SECOND_USD = 0.0000045;

// Source: https://e2b.dev/pricing (4 vCPU + 4 GiB RAM).
export const E2B_COST_PER_MS =
  (E2B_VCPU_COUNT * E2B_COST_PER_VCPU_SECOND_USD +
    E2B_MEMORY_GIB * E2B_COST_PER_GIB_SECOND_USD) /
  1000;
