"""Pydantic schemas for the Skill Builder API.

Skills are reusable, parameterized SOC capabilities (detection, enrichment,
response, reporting) that agents and workflows will be able to invoke. See
`core/storage/models.py::Skill` for the persisted shape.
"""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

SKILL_CATEGORIES = ("detection", "enrichment", "response", "reporting", "custom")


class SkillBase(BaseModel):
    """Fields shared by create/update/response."""

    name: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None
    category: str = Field(
        ..., pattern=r"^(detection|enrichment|response|reporting|custom)$"
    )
    input_schema: Dict[str, Any] = Field(default_factory=dict)
    output_schema: Dict[str, Any] = Field(default_factory=dict)
    required_tools: List[str] = Field(default_factory=list)
    prompt_template: str = Field(..., min_length=1)
    execution_steps: List[Dict[str, Any]] = Field(default_factory=list)
    is_active: bool = True


class SkillCreate(SkillBase):
    """Request body for `POST /api/skills`."""

    created_by: Optional[str] = None


class SkillUpdate(BaseModel):
    """Partial update for `PUT /api/skills/{id}`. All fields optional."""

    name: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    category: Optional[str] = Field(
        None, pattern=r"^(detection|enrichment|response|reporting|custom)$"
    )
    input_schema: Optional[Dict[str, Any]] = None
    output_schema: Optional[Dict[str, Any]] = None
    required_tools: Optional[List[str]] = None
    prompt_template: Optional[str] = Field(None, min_length=1)
    execution_steps: Optional[List[Dict[str, Any]]] = None
    is_active: Optional[bool] = None


class SkillResponse(SkillBase):
    """Full skill as returned by the API."""

    skill_id: str
    created_by: Optional[str] = None
    version: int
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class SkillDraft(SkillBase):
    """Skill generated by the AI builder, before the user saves it. No skill_id yet."""


class SkillGenerateRequest(BaseModel):
    """Request body for `POST /api/skills/generate`.

    Supports multi-turn clarification: if Claude asks a question, the client
    sends the current `conversation_history` plus the user's `user_response`.
    """

    description: str = Field(..., min_length=1)
    category: Optional[str] = Field(
        None, pattern=r"^(detection|enrichment|response|reporting|custom)$"
    )
    conversation_history: Optional[List[Dict[str, str]]] = None
    user_response: Optional[str] = None


class SkillGenerateResponse(BaseModel):
    """Response from `POST /api/skills/generate`.

    Either `needs_clarification=True` with a `message` question, or
    `needs_clarification=False` with a populated `skill` draft.
    """

    success: bool
    needs_clarification: bool = False
    message: Optional[str] = None
    conversation_history: Optional[List[Dict[str, str]]] = None
    skill: Optional[SkillDraft] = None
    error: Optional[str] = None


class SkillImportResponse(BaseModel):
    """Response from `POST /api/skills/import` (Issue #130).

    ``replaced`` is True when an existing skill with the same name was
    overwritten (and its version bumped); False when a new row was created.
    """

    skill_id: str
    name: str
    version: int
    replaced: bool
