"""Command classification policy for the unified shell_exec tool.

command_rules.yaml is generated by scripts/generate_command_data.py.
No import-time I/O here; consumers read RULES_PATH themselves.
"""
from __future__ import annotations

import os

RULES_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "command_rules.yaml")
